# Generated by Django 3.0.3 on 2020-07-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=15)),
                ('body', models.TextField()),
                ('time', models.TimeField(verbose_name='date_published')),
                ('phone_number', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=50)),
            ],
        ),
    ]
