# Generated by Django 3.0.3 on 2020-07-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('history', models.CharField(max_length=100)),
                ('directorNm', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Content_other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('referenceIdentifier', models.CharField(max_length=255)),
                ('rights', models.CharField(max_length=30)),
                ('subjectCategory', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
